-- Run this once to add popular places to all countries
-- Same pattern as seed.sql — run with:
--   sqlite3 database.db < places.sql

-- AFRICA
UPDATE countries SET places = 'Sahara Desert, Tassili n''Ajjer National Park, Casbah of Algiers, Timgad Roman Ruins, Djémila' WHERE iso2 = 'DZ';
UPDATE countries SET places = 'Kalandula Falls, Kissama National Park, Tundavala Gap, Benguela Railway, Mbanza Kongo' WHERE iso2 = 'AO';
UPDATE countries SET places = 'Royal Palaces of Abomey, Pendjari National Park, Ganvie Lake Village, Ouidah Slave Route, Dassa-Zoumé' WHERE iso2 = 'BJ';
UPDATE countries SET places = 'Okavango Delta, Chobe National Park, Makgadikgadi Pans, Tsodilo Hills, Central Kalahari Game Reserve' WHERE iso2 = 'BW';
UPDATE countries SET places = 'Sindou Peaks, Banfora Waterfalls, Tiébélé Royal Court, Ruins of Loropéni, W National Park' WHERE iso2 = 'BF';
UPDATE countries SET places = 'Kibira National Park, Lake Tanganyika, Rusizi National Park, Gishora Drum Sanctuary, Bujumbura Beaches' WHERE iso2 = 'BI';
UPDATE countries SET places = 'Sal Island Beaches, Santo Antão Mountains, Fogo Volcano, Cidade Velha, Mindelo Cultural Scene' WHERE iso2 = 'CV';
UPDATE countries SET places = 'Waza National Park, Dja Faunal Reserve, Limbe Wildlife Centre, Rhumsiki Peak, Korup National Park' WHERE iso2 = 'CM';
UPDATE countries SET places = 'Dzanga-Sangha Reserve, Boali Falls, Bangui Cathedral, Manovo-Gounda St. Floris Park, Kembe Falls' WHERE iso2 = 'CF';
UPDATE countries SET places = 'Zakouma National Park, Lake Chad, Ennedi Plateau, Tibesti Mountains, Guelta d''Archei' WHERE iso2 = 'TD';
UPDATE countries SET places = 'Mount Karthala Volcano, Mohéli Marine Park, Moroni Old Friday Mosque, Itsandra Beach, Mitsamiouli' WHERE iso2 = 'KM';
UPDATE countries SET places = 'Virunga National Park, Congo River, Lola ya Bonobo Sanctuary, Garamba National Park, Nyiragongo Volcano' WHERE iso2 = 'CD';
UPDATE countries SET places = 'Congo River, Odzala-Kokoua National Park, Pointe-Noire Beaches, Brazzaville Corniche, Lesio-Louna Reserve' WHERE iso2 = 'CG';
UPDATE countries SET places = 'Taï National Park, Basilica of Our Lady of Peace, Abidjan Plateau, Comoé National Park, Grand-Bassam' WHERE iso2 = 'CI';
UPDATE countries SET places = 'Lake Assal, Day Forest National Park, Gulf of Tadjoura, Ardoukoba Volcano, Goda Mountains' WHERE iso2 = 'DJ';
UPDATE countries SET places = 'Pyramids of Giza, Luxor Temple, Valley of the Kings, Abu Simbel, Alexandria Library' WHERE iso2 = 'EG';
UPDATE countries SET places = 'Monte Alen National Park, Bioko Island Beaches, Pico Basile, Malabo Cathedral, Ureca Beach' WHERE iso2 = 'GQ';
UPDATE countries SET places = 'Dahlak Archipelago, Asmara Art Deco City, Qohaito Archaeological Site, Debre Bizen Monastery, Massawa Old Town' WHERE iso2 = 'ER';
UPDATE countries SET places = 'Hlane Royal National Park, Mantenga Cultural Village, Mlilwane Wildlife Sanctuary, Swazi Candles Market, Sibebe Rock' WHERE iso2 = 'SZ';
UPDATE countries SET places = 'Lalibela Rock-Hewn Churches, Simien Mountains, Danakil Depression, Omo Valley, Aksum Obelisks' WHERE iso2 = 'ET';
UPDATE countries SET places = 'Lopé National Park, Ivindo National Park, Langoué Bai, Libreville Beaches, Kongou Falls' WHERE iso2 = 'GA';
UPDATE countries SET places = 'Kiang West National Park, Wassu Stone Circles, Gambia River, Abuko Nature Reserve, Janjanbureh Island' WHERE iso2 = 'GM';
UPDATE countries SET places = 'Kakum National Park, Cape Coast Castle, Mole National Park, Lake Bosomtwe, Kumasi Cultural Centre' WHERE iso2 = 'GH';
UPDATE countries SET places = 'Fouta Djallon Highlands, Mount Nimba, Conakry Grand Mosque, Bossou Chimpanzee Reserve, Îles de Los' WHERE iso2 = 'GN';
UPDATE countries SET places = 'Bijagós Archipelago, Orango National Park, Bubaque Island, João Vieira Marine Park, Cacheu Fort' WHERE iso2 = 'GW';
UPDATE countries SET places = 'Maasai Mara, Mount Kenya, Amboseli National Park, Diani Beach, Lamu Old Town' WHERE iso2 = 'KE';
UPDATE countries SET places = 'Sani Pass, Maletsunyane Falls, Sehlabathebe National Park, Thaba-Bosiu, Katse Dam' WHERE iso2 = 'LS';
UPDATE countries SET places = 'Sapo National Park, Providence Island, Kpatawee Waterfall, Lake Piso, Robertsport Surf Beach' WHERE iso2 = 'LR';
UPDATE countries SET places = 'Leptis Magna, Sabratha Roman Theatre, Ghadamès Old Town, Akakus Rock Art, Tripoli Old City' WHERE iso2 = 'LY';
UPDATE countries SET places = 'Avenue of the Baobabs, Tsingy de Bemaraha, Nosy Be Island, Ranomafana National Park, Isalo National Park' WHERE iso2 = 'MG';
UPDATE countries SET places = 'Lake Malawi, Liwonde National Park, Mulanje Massif, Nyika Plateau, Cape Maclear' WHERE iso2 = 'MW';
UPDATE countries SET places = 'Djenné Great Mosque, Timbuktu, Dogon Country, Bamako Grand Marché, Hombori Tondo' WHERE iso2 = 'ML';
UPDATE countries SET places = 'Banc d''Arguin National Park, Chinguetti Ancient Library, Terjit Oasis, Richat Structure, Ouadane' WHERE iso2 = 'MR';
UPDATE countries SET places = 'Le Morne Brabant, Chamarel Coloured Earths, Black River Gorges, Blue Bay Marine Park, Port Louis Market' WHERE iso2 = 'MU';
UPDATE countries SET places = 'Jemaa el-Fna, Fes Medina, Sahara Desert Erg Chebbi, Hassan II Mosque, Chefchaouen Blue City' WHERE iso2 = 'MA';
UPDATE countries SET places = 'Gorongosa National Park, Bazaruto Archipelago, Tofo Beach, Island of Mozambique, Ponta do Ouro' WHERE iso2 = 'MZ';
UPDATE countries SET places = 'Sossusvlei Dunes, Etosha National Park, Fish River Canyon, Skeleton Coast, Kolmanskop Ghost Town' WHERE iso2 = 'NA';
UPDATE countries SET places = 'W National Park, Agadez Grand Mosque, Aïr Mountains, Tenere Desert, Zinder Sultan''s Palace' WHERE iso2 = 'NE';
UPDATE countries SET places = 'Olumo Rock, Yankari National Park, Zuma Rock, Lekki Conservation Centre, Osun-Osogbo Sacred Grove' WHERE iso2 = 'NG';
UPDATE countries SET places = 'Volcanoes National Park, Lake Kivu, Nyungwe Forest, Kigali Genocide Memorial, Akagera National Park' WHERE iso2 = 'RW';
UPDATE countries SET places = 'Obo Natural Park, Praia das Conchas, Pico Cão Grande, São Tomé Plantation Houses, Bom Bom Island' WHERE iso2 = 'ST';
UPDATE countries SET places = 'Pink Lake Retba, Goree Island, Djoudj Bird Sanctuary, Casamance River, Bandia Wildlife Reserve' WHERE iso2 = 'SN';
UPDATE countries SET places = 'Tacugama Chimpanzee Sanctuary, Tiwai Island, Bunce Island, Outamba-Kilimi National Park, Banana Islands' WHERE iso2 = 'SL';
UPDATE countries SET places = 'Laas Geel Cave Paintings, Mogadishu Cathedral Ruins, Liido Beach, Hobyo Ruins, Xamar Weyne Old Town' WHERE iso2 = 'SO';
UPDATE countries SET places = 'Kruger National Park, Table Mountain, Robben Island, Cape Winelands, Drakensberg Mountains' WHERE iso2 = 'ZA';
UPDATE countries SET places = 'Boma National Park, White Nile, Nimule National Park, Juba Cathedral, Bandingilo National Park' WHERE iso2 = 'SS';
UPDATE countries SET places = 'Meroe Pyramids, Jebel Barkal, Dinder National Park, Khartoum Confluence, Suakin Old Port' WHERE iso2 = 'SD';
UPDATE countries SET places = 'Serengeti National Park, Kilimanjaro, Zanzibar Stone Town, Ngorongoro Crater, Selous Game Reserve' WHERE iso2 = 'TZ';
UPDATE countries SET places = 'Koutammakou Landscape, Fazao-Malfakassa National Park, Togoville Village, Lomé Grand Marché, Cascade de Kpimé' WHERE iso2 = 'TG';
UPDATE countries SET places = 'Carthage Ruins, Medina of Tunis, El Djem Amphitheatre, Sidi Bou Said, Dougga' WHERE iso2 = 'TN';
UPDATE countries SET places = 'Bwindi Impenetrable Forest, Murchison Falls, Queen Elizabeth National Park, Ssese Islands, Jinja Source of the Nile' WHERE iso2 = 'UG';
UPDATE countries SET places = 'Victoria Falls, South Luangwa National Park, Lower Zambezi, Kafue National Park, Lake Kariba' WHERE iso2 = 'ZM';
UPDATE countries SET places = 'Victoria Falls, Great Zimbabwe Ruins, Hwange National Park, Matobo Hills, Lake Kariba' WHERE iso2 = 'ZW';

-- ASIA
UPDATE countries SET places = 'Band-e-Amir Lakes, Minaret of Jam, Bamiyan Valley, Wakhan Corridor, Kabul Old Bazaar' WHERE iso2 = 'AF';
UPDATE countries SET places = 'Geghard Monastery, Lake Sevan, Tatev Monastery, Garni Temple, Yerevan Cascade' WHERE iso2 = 'AM';
UPDATE countries SET places = 'Old City of Baku, Gobustan Rock Art, Mud Volcanoes, Sheki Khan''s Palace, Yanar Dag Fire Mountain' WHERE iso2 = 'AZ';
UPDATE countries SET places = 'Al-Fateh Grand Mosque, Bahrain Fort, Tree of Life, Manama Souq, Bahrain National Museum' WHERE iso2 = 'BH';
UPDATE countries SET places = 'Sundarbans Mangrove Forest, Cox''s Bazar Beach, Shat Gombuj Mosque, Ahsan Manzil, Rangamati Hill District' WHERE iso2 = 'BD';
UPDATE countries SET places = 'Tiger''s Nest Monastery, Punakha Dzong, Dochula Pass, Paro Valley, Bumthang Sacred Lakes' WHERE iso2 = 'BT';
UPDATE countries SET places = 'Omar Ali Saifuddien Mosque, Ulu Temburong National Park, Royal Regalia Museum, Kampong Ayer Water Village, Jerudong Park' WHERE iso2 = 'BN';
UPDATE countries SET places = 'Angkor Wat, Bayon Temple, Tonle Sap Lake, Royal Palace Phnom Penh, Koh Rong Island' WHERE iso2 = 'KH';
UPDATE countries SET places = 'Great Wall of China, Forbidden City, Terra Cotta Army, Li River, Zhangjiajie National Park' WHERE iso2 = 'CN';
UPDATE countries SET places = 'Aphrodite Hills, Troodos Mountains, Kykkos Monastery, Paphos Archaeological Park, Cape Greco' WHERE iso2 = 'CY';
UPDATE countries SET places = 'Old Town Tbilisi, Vardzia Cave City, Kazbegi Mountains, Uplistsikhe Cave Town, Sighnaghi Wine Town' WHERE iso2 = 'GE';
UPDATE countries SET places = 'Taj Mahal, Jaipur Pink City, Kerala Backwaters, Varanasi Ghats, Hampi Ruins' WHERE iso2 = 'IN';
UPDATE countries SET places = 'Bali Temples, Borobudur, Komodo Island, Raja Ampat Islands, Prambanan Temple' WHERE iso2 = 'ID';
UPDATE countries SET places = 'Persepolis, Isfahan Imam Square, Nasir ol-Molk Mosque, Golestan Palace, Shiraz Gardens' WHERE iso2 = 'IR';
UPDATE countries SET places = 'Babylon Ruins, Ziggurat of Ur, Erbil Citadel, Al-Askari Shrine, Ctesiphon Arch' WHERE iso2 = 'IQ';
UPDATE countries SET places = 'Jerusalem Old City, Dead Sea, Masada, Tel Aviv Beaches, Caesarea National Park' WHERE iso2 = 'IL';
UPDATE countries SET places = 'Mount Fuji, Kyoto Temples, Tokyo Shibuya, Hiroshima Peace Memorial, Nara Deer Park' WHERE iso2 = 'JP';
UPDATE countries SET places = 'Petra, Wadi Rum Desert, Dead Sea, Jerash Roman City, Aqaba Red Sea' WHERE iso2 = 'JO';
UPDATE countries SET places = 'Charyn Canyon, Altyn-Emel National Park, Baikonur Cosmodrome, Nur-Sultan Bayterek Tower, Kolsai Lakes' WHERE iso2 = 'KZ';
UPDATE countries SET places = 'Kuwait Towers, Grand Mosque, Failaka Island, Al Shaheed Park, Mirror House' WHERE iso2 = 'KW';
UPDATE countries SET places = 'Ala Archa National Park, Song Kul Lake, Burana Tower, Tash Rabat Caravanserai, Issyk-Kul Lake' WHERE iso2 = 'KG';
UPDATE countries SET places = 'Luang Prabang, Plain of Jars, Kuang Si Waterfalls, Vang Vieng, Si Phan Don Four Thousand Islands' WHERE iso2 = 'LA';
UPDATE countries SET places = 'Jeita Grotto, Byblos Ancient City, Baalbek Roman Temples, Qadisha Valley, Beirut Corniche' WHERE iso2 = 'LB';
UPDATE countries SET places = 'Petronas Twin Towers, Batu Caves, George Town Penang, Mount Kinabalu, Langkawi Island' WHERE iso2 = 'MY';
UPDATE countries SET places = 'Overwater Bungalows, Male Friday Mosque, Banana Reef, Vaadhoo Bioluminescent Beach, Ari Atoll' WHERE iso2 = 'MV';
UPDATE countries SET places = 'Gobi Desert, Khuvsgul Lake, Orkhon Valley, Karakorum Ancient Capital, Terelj National Park' WHERE iso2 = 'MN';
UPDATE countries SET places = 'Bagan Temples, Inle Lake, Shwedagon Pagoda, Mandalay Palace, Ngapali Beach' WHERE iso2 = 'MM';
UPDATE countries SET places = 'Everest Base Camp, Kathmandu Durbar Square, Chitwan National Park, Pokhara Lake, Lumbini Buddha Birthplace' WHERE iso2 = 'NP';
UPDATE countries SET places = 'Kumsusan Palace, Juche Tower, Pyongyang Metro, Mount Paektu, DMZ Border' WHERE iso2 = 'KP';
UPDATE countries SET places = 'Muscat Old Town, Wahiba Sands Desert, Wadi Shab, Jebel Akhdar Mountains, Nizwa Fort' WHERE iso2 = 'OM';
UPDATE countries SET places = 'Lahore Fort, Mohenjo-daro Ruins, Karakoram Highway, Fairy Meadows, Hunza Valley' WHERE iso2 = 'PK';
UPDATE countries SET places = 'Church of Nativity Bethlehem, Hisham''s Palace, Hebron Old City, Wadi Qelt, Nablus Old Soap Factories' WHERE iso2 = 'PS';
UPDATE countries SET places = 'Chocolate Hills, Tubbataha Reef, Rice Terraces of Banaue, Palawan Underground River, Mayon Volcano' WHERE iso2 = 'PH';
UPDATE countries SET places = 'Museum of Islamic Art, Souq Waqif, Pearl Monument, Katara Cultural Village, Al Zubarah Fort' WHERE iso2 = 'QA';
UPDATE countries SET places = 'Masjid al-Haram Mecca, Al-Ula Ancient City, Edge of the World Riyadh, Al-Masmak Fortress, Rub al Khali Desert' WHERE iso2 = 'SA';
UPDATE countries SET places = 'Gardens by the Bay, Marina Bay Sands, Sentosa Island, Hawker Centres, Singapore Zoo' WHERE iso2 = 'SG';
UPDATE countries SET places = 'Gyeongbokgung Palace, Jeju Island, Bukchon Hanok Village, DMZ, Seoraksan National Park' WHERE iso2 = 'KR';
UPDATE countries SET places = 'Sigiriya Rock Fortress, Temple of the Tooth, Yala National Park, Mirissa Beach, Ella Tea Country' WHERE iso2 = 'LK';
UPDATE countries SET places = 'Umayyad Mosque Damascus, Palmyra Ruins, Krak des Chevaliers, Aleppo Citadel, Dead Cities' WHERE iso2 = 'SY';
UPDATE countries SET places = 'Taroko Gorge, Sun Moon Lake, Jiufen Old Street, Alishan Forest, Taipei 101' WHERE iso2 = 'TW';
UPDATE countries SET places = 'Hissar Fortress, Fann Mountains, Iskanderkul Lake, Istaravshan Old Town, Khujand Panjshanbe Bazaar' WHERE iso2 = 'TJ';
UPDATE countries SET places = 'Grand Palace Bangkok, Chiang Mai Temples, Phi Phi Islands, Ayutthaya Ruins, Pai Valley' WHERE iso2 = 'TH';
UPDATE countries SET places = 'Jaco Island, Cristo Rei Statue, Atauro Island, Maubisse Highland, Resistance Museum Dili' WHERE iso2 = 'TL';
UPDATE countries SET places = 'Hagia Sophia, Cappadocia, Ephesus Ruins, Pamukkale Thermal Pools, Grand Bazaar Istanbul' WHERE iso2 = 'TR';
UPDATE countries SET places = 'Darvaza Gas Crater, Ancient Merv, Kow Ata Underground Lake, Nisa Ruins, Yangykala Canyon' WHERE iso2 = 'TM';
UPDATE countries SET places = 'Burj Khalifa Dubai, Sheikh Zayed Grand Mosque, Dubai Mall, Liwa Oasis, Al Ain Oasis' WHERE iso2 = 'AE';
UPDATE countries SET places = 'Registan Square Samarkand, Bukhara Old City, Khiva Itchan Kala, Aral Sea, Fergana Valley' WHERE iso2 = 'UZ';
UPDATE countries SET places = 'Ha Long Bay, Hoi An Ancient Town, My Son Sanctuary, Phong Nha Caves, Sapa Rice Terraces' WHERE iso2 = 'VN';
UPDATE countries SET places = 'Old City Sanaa, Socotra Island, Wadi Hadramawt, Marib Dam Ruins, Aden Old Town' WHERE iso2 = 'YE';

-- EUROPE
UPDATE countries SET places = 'Gjirokaster Castle, Butrint National Park, Albanian Riviera, Berat Old City, Valbona Valley' WHERE iso2 = 'AL';
UPDATE countries SET places = 'Grandvalira Ski Resort, Casa de la Vall, Meritxell Sanctuary, Caldea Spa, Madriu-Perafita-Claror Valley' WHERE iso2 = 'AD';
UPDATE countries SET places = 'Vienna Schonbrunn Palace, Hallstatt Village, Salzburg Old Town, Innsbruck, Wachau Valley' WHERE iso2 = 'AT';
UPDATE countries SET places = 'Mir Castle, Nesvizh Castle, Bialowieza Forest, Braslav Lakes, Minsk Independence Square' WHERE iso2 = 'BY';
UPDATE countries SET places = 'Grand Place Brussels, Bruges Medieval Centre, Ghent Gravensteen Castle, Ardennes Forest, Antwerp Cathedral' WHERE iso2 = 'BE';
UPDATE countries SET places = 'Sarajevo Old Bazaar, Mostar Old Bridge, Kravice Waterfalls, Una National Park, Blagaj Tekija' WHERE iso2 = 'BA';
UPDATE countries SET places = 'Rila Monastery, Plovdiv Old Town, Pirin National Park, Varna Black Sea Coast, Nessebar Ancient City' WHERE iso2 = 'BG';
UPDATE countries SET places = 'Dubrovnik Old Town, Plitvice Lakes, Diocletian Palace Split, Hvar Island, Krka Waterfalls' WHERE iso2 = 'HR';
UPDATE countries SET places = 'Prague Old Town Square, Cesky Krumlov, Karlovy Vary, Kutna Hora, Bohemian Switzerland' WHERE iso2 = 'CZ';
UPDATE countries SET places = 'Nyhavn Copenhagen, Tivoli Gardens, Kronborg Castle, Legoland, Faroe Islands' WHERE iso2 = 'DK';
UPDATE countries SET places = 'Tallinn Old Town, Lahemaa National Park, Saaremaa Island, Tartu University Town, Parnu Beach' WHERE iso2 = 'EE';
UPDATE countries SET places = 'Helsinki Cathedral, Rovaniemi Santa Village, Nuuksio National Park, Turku Castle, Northern Lights Lapland' WHERE iso2 = 'FI';
UPDATE countries SET places = 'Eiffel Tower, Louvre Museum, Palace of Versailles, Notre-Dame Cathedral, Mont Saint-Michel' WHERE iso2 = 'FR';
UPDATE countries SET places = 'Brandenburg Gate Berlin, Neuschwanstein Castle, Black Forest, Cologne Cathedral, Rhine Valley' WHERE iso2 = 'DE';
UPDATE countries SET places = 'Acropolis Athens, Santorini, Meteora Monasteries, Delphi, Rhodes Old Town' WHERE iso2 = 'GR';
UPDATE countries SET places = 'Budapest Parliament, Fisherman Bastion, Lake Balaton, Eger Castle, Puszta Plain' WHERE iso2 = 'HU';
UPDATE countries SET places = 'Blue Lagoon, Northern Lights, Geysir, Skogafoss Waterfall, Reykjavik Old Harbour' WHERE iso2 = 'IS';
UPDATE countries SET places = 'Cliffs of Moher, Ring of Kerry, Trinity College Dublin, Giant Causeway, Killarney National Park' WHERE iso2 = 'IE';
UPDATE countries SET places = 'Colosseum, Vatican City, Amalfi Coast, Pompeii, Cinque Terre' WHERE iso2 = 'IT';
UPDATE countries SET places = 'Prizren Old Town, Rugova Canyon, Visoki Decani Monastery, Germia Park, Gadime Cave' WHERE iso2 = 'XK';
UPDATE countries SET places = 'Riga Old Town, Jurmala Beach, Gauja National Park, Rundale Palace, Cape Kolka' WHERE iso2 = 'LV';
UPDATE countries SET places = 'Vaduz Castle, Rhine Valley Hike, Gutenberg Castle, Liechtenstein National Museum, Malbun Ski Resort' WHERE iso2 = 'LI';
UPDATE countries SET places = 'Vilnius Old Town, Trakai Island Castle, Curonian Spit, Hill of Crosses, Aukstaitija National Park' WHERE iso2 = 'LT';
UPDATE countries SET places = 'Luxembourg City Casemates, Vianden Castle, Mullerthal Trail, Moselle Wine Region, Bourscheid Castle' WHERE iso2 = 'LU';
UPDATE countries SET places = 'Valletta Grand Harbour, Hagar Qim Temples, Blue Lagoon Comino, Mdina Silent City, St Johns Co-Cathedral' WHERE iso2 = 'MT';
UPDATE countries SET places = 'Orheiul Vechi Monastery, Cricova Wine Cellars, Soroca Fortress, Transnistria, Chisinau Central Market' WHERE iso2 = 'MD';
UPDATE countries SET places = 'Monte Carlo Casino, Prince Palace, Oceanographic Museum, Formula 1 Circuit, Larvotto Beach' WHERE iso2 = 'MC';
UPDATE countries SET places = 'Bay of Kotor, Durmitor National Park, Sveti Stefan Island, Biogradska Gora, Ostrog Monastery' WHERE iso2 = 'ME';
UPDATE countries SET places = 'Anne Frank House Amsterdam, Rijksmuseum, Keukenhof Gardens, Van Gogh Museum, Kinderdijk Windmills' WHERE iso2 = 'NL';
UPDATE countries SET places = 'Lake Ohrid, Matka Canyon, Skopje Stone Bridge, Mavrovo National Park, Bitola Ancient Heraclea' WHERE iso2 = 'MK';
UPDATE countries SET places = 'Fjords of Norway, Northern Lights Tromso, Geirangerfjord, Bryggen Bergen, Lofoten Islands' WHERE iso2 = 'NO';
UPDATE countries SET places = 'Krakow Old Town, Wieliczka Salt Mine, Auschwitz Memorial, Warsaw Old Town, Bialowieza Forest' WHERE iso2 = 'PL';
UPDATE countries SET places = 'Lisbon Alfama, Sintra Palaces, Douro Valley Vineyards, Algarve Beaches, Porto Ribeira' WHERE iso2 = 'PT';
UPDATE countries SET places = 'Transylvania Bran Castle, Bucharest Palace of Parliament, Danube Delta, Painted Monasteries Bucovina, Sibiu Medieval Town' WHERE iso2 = 'RO';
UPDATE countries SET places = 'Red Square Moscow, Trans-Siberian Railway, Hermitage Museum St Petersburg, Lake Baikal, Kamchatka Volcanoes' WHERE iso2 = 'RU';
UPDATE countries SET places = 'Mount Titano, Guaita Tower, San Marino Historic Centre, Palazzo Pubblico, Three Towers of San Marino' WHERE iso2 = 'SM';
UPDATE countries SET places = 'Belgrade Kalemegdan Fortress, Djerdap National Park, Novi Sad Petrovaradin, Studenica Monastery, Zlatibor Mountain' WHERE iso2 = 'RS';
UPDATE countries SET places = 'Bratislava Old Town, High Tatras, Bojnice Castle, Slovak Paradise National Park, Banska Stiavnica' WHERE iso2 = 'SK';
UPDATE countries SET places = 'Lake Bled, Postojna Cave, Ljubljana Old Town, Triglav National Park, Piran Venetian Town' WHERE iso2 = 'SI';
UPDATE countries SET places = 'Sagrada Familia Barcelona, Alhambra Granada, Park Guell, Toledo Old City, Guggenheim Museum Bilbao' WHERE iso2 = 'ES';
UPDATE countries SET places = 'Stockholm Gamla Stan, ABBA Museum, Abisko Northern Lights, Gothenburg Archipelago, Visby Medieval Town' WHERE iso2 = 'SE';
UPDATE countries SET places = 'Matterhorn, Jungfraujoch, Lake Geneva, Bern Old Town, Rhine Falls' WHERE iso2 = 'CH';
UPDATE countries SET places = 'Kyiv Pechersk Lavra, Lviv Old Town, Chernobyl Exclusion Zone, Carpathian Mountains, Sofiyivka Park' WHERE iso2 = 'UA';
UPDATE countries SET places = 'Big Ben, Buckingham Palace, Stonehenge, Tower of London, Lake District' WHERE iso2 = 'GB';
UPDATE countries SET places = 'St Peters Basilica, Sistine Chapel, Vatican Museums, St Peters Square, Castel Sant Angelo' WHERE iso2 = 'VA';

-- NORTH AMERICA
UPDATE countries SET places = 'Nelson Dockyard, Devil Bridge, Shirley Heights, Half Moon Bay, Dickenson Bay Beach' WHERE iso2 = 'AG';
UPDATE countries SET places = 'Nassau Paradise Island, Exuma Pigs Swimming Beach, Thunderball Grotto, Dean Blue Hole, Harbour Island Pink Sand' WHERE iso2 = 'BS';
UPDATE countries SET places = 'Bridgetown Historic Area, Harrison Cave, Bathsheba Soup Bowl, Andromeda Botanic Gardens, Oistins Fish Fry' WHERE iso2 = 'BB';
UPDATE countries SET places = 'Great Blue Hole, Belize Barrier Reef, Caracol Maya Ruins, Actun Tunichil Muknal Cave, Lamanai' WHERE iso2 = 'BZ';
UPDATE countries SET places = 'Banff National Park, Niagara Falls, Old Quebec City, Vancouver Stanley Park, Northern Lights Yukon' WHERE iso2 = 'CA';
UPDATE countries SET places = 'Monteverde Cloud Forest, Arenal Volcano, Manuel Antonio National Park, Tortuguero, Corcovado National Park' WHERE iso2 = 'CR';
UPDATE countries SET places = 'Old Havana, Vinales Valley, Trinidad Colonial Town, Varadero Beach, Bay of Pigs' WHERE iso2 = 'CU';
UPDATE countries SET places = 'Boiling Lake, Morne Trois Pitons National Park, Champagne Reef Diving, Trafalgar Falls, Kalinago Territory' WHERE iso2 = 'DM';
UPDATE countries SET places = 'Punta Cana Beaches, Santo Domingo Colonial Zone, Samana Peninsula, Los Haitises National Park, Jarabacoa Mountains' WHERE iso2 = 'DO';
UPDATE countries SET places = 'Ruta de las Flores, Joya de Ceren, Tazumal Maya Ruins, Coatepeque Lake, El Imposible National Park' WHERE iso2 = 'SV';
UPDATE countries SET places = 'Grand Anse Beach, Annandale Falls, Fort Frederick, Belmont Estate Chocolate Tour, Underwater Sculpture Park' WHERE iso2 = 'GD';
UPDATE countries SET places = 'Tikal National Park, Lake Atitlan, Antigua Guatemala, Semuc Champey, Chichicastenango Market' WHERE iso2 = 'GT';
UPDATE countries SET places = 'Citadelle Laferriere, Sans-Souci Palace, Bassin Bleu, Labadee Beach, Jacmel Art Town' WHERE iso2 = 'HT';
UPDATE countries SET places = 'Copan Maya Ruins, Roatan Island, Pico Bonito National Park, Lake Yojoa, Cayos Cochinos' WHERE iso2 = 'HN';
UPDATE countries SET places = 'Dunns River Falls, Blue Mountains, Bob Marley Museum, Doctors Cave Beach, YS Falls' WHERE iso2 = 'JM';
UPDATE countries SET places = 'Chichen Itza, Teotihuacan Pyramids, Palenque, Copper Canyon, Oaxaca Monte Alban' WHERE iso2 = 'MX';
UPDATE countries SET places = 'Ometepe Island, Granada Colonial City, Masaya Volcano, Corn Islands, Somoto Canyon' WHERE iso2 = 'NI';
UPDATE countries SET places = 'Panama Canal, San Blas Islands, Bocas del Toro, Casco Viejo Panama City, Darien National Park' WHERE iso2 = 'PA';
UPDATE countries SET places = 'Brimstone Hill Fortress, South East Peninsula Beaches, Timothy Hill, Pinneys Beach Nevis, Botanical Gardens' WHERE iso2 = 'KN';
UPDATE countries SET places = 'The Pitons, Marigot Bay, Soufriere Drive-in Volcano, Anse Chastanet Beach, Diamond Botanical Gardens' WHERE iso2 = 'LC';
UPDATE countries SET places = 'Tobago Cays Marine Park, La Soufriere Volcano, Fort Charlotte, Bequia Island, Wallilabou Bay' WHERE iso2 = 'VC';
UPDATE countries SET places = 'Caroni Bird Sanctuary, Maracas Beach, Asa Wright Nature Centre, Pitch Lake, Port of Spain Savannah' WHERE iso2 = 'TT';
UPDATE countries SET places = 'Grand Canyon, Yellowstone National Park, New York City, Walt Disney World, Hawaii Volcanoes' WHERE iso2 = 'US';

-- OCEANIA
UPDATE countries SET places = 'Sydney Opera House, Great Barrier Reef, Uluru, Daintree Rainforest, Great Ocean Road' WHERE iso2 = 'AU';
UPDATE countries SET places = 'Mamanuca Islands, Garden of the Sleeping Giant, Sabeto Hot Springs, Sigatoka Sand Dunes, Yasawa Islands' WHERE iso2 = 'FJ';
UPDATE countries SET places = 'Tarawa Atoll WWII Sites, Christmas Island, Millennium Island, Phoenix Islands Protected Area, South Tarawa' WHERE iso2 = 'KI';
UPDATE countries SET places = 'Bikini Atoll Nuclear Test Site, Majuro Lagoon, Mili Atoll, Laura Beach, Alele Museum' WHERE iso2 = 'MH';
UPDATE countries SET places = 'Nan Madol Ancient City, Chuuk Lagoon Wreck Diving, Sokehs Rock, Kepirohi Waterfall, Yap Stone Money' WHERE iso2 = 'FM';
UPDATE countries SET places = 'Buada Lagoon, Command Ridge WWII Site, Anibare Bay, Nauru Phosphate Cantilever, Menen Hotel' WHERE iso2 = 'NR';
UPDATE countries SET places = 'Milford Sound, Hobbiton, Queenstown Adventure Capital, Bay of Islands, Tongariro National Park' WHERE iso2 = 'NZ';
UPDATE countries SET places = 'Rock Islands Southern Lagoon, Jellyfish Lake, Ngardmau Waterfall, Peleliu WWII Battlefield, Koror Town' WHERE iso2 = 'PW';
UPDATE countries SET places = 'Kokoda Track, Mount Wilhelm, Tufi Fjords, Sepik River, Rabaul Volcano' WHERE iso2 = 'PG';
UPDATE countries SET places = 'To Sua Ocean Trench, Lalomanu Beach, Robert Louis Stevenson Museum, Papasea Sliding Rocks, Fagaloa Bay' WHERE iso2 = 'WS';
UPDATE countries SET places = 'Guadalcanal WWII Memorials, Marovo Lagoon, Tetepare Island, Skull Island Roviana, Tenaru River' WHERE iso2 = 'SB';
UPDATE countries SET places = 'Haamonga a Maui Trilithon, Eua National Park, Vavau Islands, Swallows Cave, Anahulu Cave' WHERE iso2 = 'TO';
UPDATE countries SET places = 'Funafuti Atoll, Tuvalu Marine Conservation Area, Fongafale Island, Funafala, Te Namo Lagoon' WHERE iso2 = 'TV';
UPDATE countries SET places = 'Mount Yasur Volcano, Champagne Beach, Millennium Cave, Mele Cascades, Nanda Blue Hole' WHERE iso2 = 'VU';

-- SOUTH AMERICA
UPDATE countries SET places = 'Iguazu Falls, Patagonia, Buenos Aires Recoleta, Perito Moreno Glacier, Mendoza Wine Region' WHERE iso2 = 'AR';
UPDATE countries SET places = 'Lake Titicaca, Salar de Uyuni Salt Flat, Tiwanaku Ruins, Yungas Road Death Road, Madidi National Park' WHERE iso2 = 'BO';
UPDATE countries SET places = 'Iguazu Falls, Christ the Redeemer, Amazon Rainforest, Pantanal Wetlands, Fernando de Noronha' WHERE iso2 = 'BR';
UPDATE countries SET places = 'Torres del Paine, Atacama Desert, Easter Island, Valle de la Luna, Chiloe Island' WHERE iso2 = 'CL';
UPDATE countries SET places = 'Cartagena Walled City, Tayrona National Park, Coffee Region, Ciudad Perdida, Cano Cristales River' WHERE iso2 = 'CO';
UPDATE countries SET places = 'Galapagos Islands, Amazon Napo River, Quilotoa Crater Lake, Ingapirca Inca Ruins, Cotopaxi Volcano' WHERE iso2 = 'EC';
UPDATE countries SET places = 'Kaieteur Falls, Rupununi Savanna, Iwokrama Rainforest, Shell Beach, Georgetown Stabroek Market' WHERE iso2 = 'GY';
UPDATE countries SET places = 'Itaipu Dam, Jesuit Missions, Ybycui National Park, Cerro Cora National Park, Asuncion Palacio de Lopez' WHERE iso2 = 'PY';
UPDATE countries SET places = 'Machu Picchu, Lake Titicaca, Nazca Lines, Colca Canyon, Huascaran National Park' WHERE iso2 = 'PE';
UPDATE countries SET places = 'Central Suriname Nature Reserve, Brownsberg Nature Park, Paramaribo Wooden Architecture, Galibi Turtle Beach, Blanche Marie Falls' WHERE iso2 = 'SR';
UPDATE countries SET places = 'Punta del Este, Colonia del Sacramento, Cabo Polonio, Valle del Lunarejo, Montevideo Ciudad Vieja' WHERE iso2 = 'UY';
UPDATE countries SET places = 'Angel Falls, Los Roques Archipelago, Canaima National Park, Merida Cable Car, Morrocoy National Park' WHERE iso2 = 'VE';
